### ISSUE TITLE
Missing 'tags' in the GitHub project openjfx/samples.

### ISSUE THREAD

**Issue by Naoghuman** [openjfx/samples#10]
Missing 'tags' in the GitHub project openjfx/samples.

Some suggestions for 'tags' for the GitHub project:
* openjfx
* javafx-11
* java-11
* examples
* docmentation
* maven
* gradle
* intellij
* netbeans
* eclipse

**Comment by jperedadnr** [comment]
I've added these tags, thanks for pointing this out.
