### ISSUE TITLE
Gradle task 'Debug' fails in Netbeans 9.0 for hellofx

### ISSUE THREAD

**Issue by ThomasDaheim** [openjfx/samples#2]
When running the 'Debug' task in Netbeans 9.0 with config

- Apache NetBeans IDE 9.0 (Build incubator-netbeans-release-334-on-20180708)
- Groovy Plugin 1.35
- Gradle Plugin 2.0.1
- Gradle 4.10.2

I get the following error:

```
> Task :debug
Listening for transport dt_socket at address: 5005
Error: JavaFX runtime components are missing, and are required to run this application
```

So it seems the following section in build.gradle doesn't also work for 'Debug'?
```
run {
    doFirst {
        jvmArgs = [
                '--module-path', classpath.asPath,
                '--add-modules', 'javafx.controls'
        ]
    }
}
```

**Comment by jperedadnr** [comment]
A possible solution for debugging is adding a debug task, where you can set the module-path, and add the modules.

I've tested this successfully:

```
task(runDebug, dependsOn: 'classes', type: JavaExec) {
    main = "org.openjfx.MainApp"
    classpath = sourceSets.main.runtimeClasspath
    jvmArgs = ['--module-path', classpath.asPath,
                '--add-modules', 'javafx.controls',
                '--add-modules', 'javafx.fxml',
                "-Xdebug",
                "-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005"]
}
```

You run the task `./gradlew runDebug`, and then on NetBeans you attach a debugger on that port.

**Comment by ThomasDaheim** [comment]
Thanks, that seems to do the trick!

A bit inconvenient to start the debugger manually... So I will check with the developer of the Netbeans Gradle plugin on how to extend the ex. "debug" task properly - that doesn't seem to work with above modifications.

**Comment by ThomasDaheim** [comment]
As discussed in https://github.com/kelemen/netbeans-gradle-project/issues/403 a good tip was to not overwrite the _jvmArgs_ but to extend them using

```
def newArgs = [/* Your args go here */]
jvmArgs = jvmArgs.plus(newArgs)
```

So I avoided conflict with the Netbeans Gradle PlugIn. Maybe that would be something for your documentation as well?

**Comment by jperedadnr** [comment]
Probably a section about debugging can be included in the docs, indeed.

About the use of `plus`, I don't think that is required when you are setting the VM arguments, but it is more important the order of those arguments.

Taken from your [comment](https://github.com/kelemen/netbeans-gradle-project/issues/403), this works for me, to run and debug (directly from the NetBeans Debug button):

```
run {
    doFirst {
        jvmArgs = [
                '--module-path', classpath.asPath,
                '--add-modules', 'javafx.controls'
        ]
    }
}

task(debug, dependsOn: 'classes', type: JavaExec) {
    doFirst {
        main = 'org.openjfx.MainApp'
        classpath = sourceSets.main.runtimeClasspath
        jvmArgs = [
                '--module-path', classpath.asPath,
                "-Xdebug",
                "-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005",
                '--add-modules', 'javafx.controls',
                '--add-exports', 'javafx.graphics/com.sun.javafx.util=ALL-UNNAMED',
                '--add-exports', 'javafx.base/com.sun.javafx.reflect=ALL-UNNAMED',
                '--add-exports', 'javafx.base/com.sun.javafx.beans=ALL-UNNAMED',
                ]
    }
}
```

**Comment by ThomasDaheim** [comment]
Yep, that seems to work for me as well for "Debug".

Still I find the ```def newArgs...``` together with ```jvmArgs = jvmArgs.plus(newArgs)``` more sueful, since I only have to write the long list once and not twice for the "Run" and "Debug" task. In m case I need to add 15 (!) ```--add-exports``` to get things going.
