### ISSUE TITLE
I don't know where else to open this...

### ISSUE THREAD

**Issue by veganaiZe** [openjfx/samples#27]
```
Error: Could not find or load main class HelloFX
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```
Apparently the openjfx 11.0.2 sdk doesn't include the `Application` class.

**Comment by veganaize** [comment]
My bad!
I was using incorrect command line.
Needed:
`java --module-path %PATH_TO_FX% --add-modules javafx.controls HelloFX`
