### ISSUE TITLE
build fails after adding more modules to build.gradle 

### ISSUE THREAD

**Issue by oxmon-2500** [openjfx/samples#29]
After adding a module to build.gradle:
javafx {
    version = "12"
    modules = [ 'javafx.controls' ]
    modules = [ 'javafx.media' ]
}
"./gradlew build" produces an error "package javafx.scene.control does not exist"

OS: centos 64, java 12.0.1

**Comment by jperedadnr** [comment]
You need to add all the requierd JavaFX modules to the same list:
```
javafx {
version = "12"
modules = [ 'javafx.controls'`, 'javafx.media' ]
}
``

**Comment by oxmon-2500** [comment]
Thank you for your answer. Shame of me, I oversaw the 's' in modules! Everything works fine.
