### ISSUE TITLE
Sample Gradle project doesn't build a working application

### ISSUE THREAD

**Issue by trejkaz** [openjfx/samples#31]
I'm just trying to get a simple application up and running from an actual build. I thought the project here might provide a working example, but it turns out that it builds a non-working distribution.

Reproduction:

```
> git clone https://github.com/openjfx/samples
> cd samples\HelloFX\Gradle\hellofx
> set JAVA_HOME="c:\Program Files\Java\jdk-11.0.3"
> gradlew distZip
> cd build\distributions
> unzip hellofx.zip
> cd hellofx\bin
> hellofx.bat
```

Result:

> Error: JavaFX runtime components are missing, and are required to run this application

Am I doing something wrong? I was under the impression that the JavaFX jars fetched via Gradle would be the components it's supposed to be using.

**Comment by jperedadnr** [comment]
The usual tasks like `distZip` or even `jar` don't deal with the JavaFX dependencies unless you modify them to do so.

The JavaFX Gradle plugin helps you running the project, but it is not intended for distribution tasks.

Options:

- Create a Fat/Shadow Jar if your project is not modular: https://openjfx.io/openjfx-docs/#modular, section Non-modular project with Gradle.

- Use jlink to create a runtime image if your project is modular: https://openjfx.io/openjfx-docs/#modular, section Modular with Gradle.

**Comment by trejkaz** [comment]
Huh... What's the point then, if I'm the only one who can run it. :/

**Comment by jperedadnr** [comment]
As mentioned, the JavaFX gradle plugin helps you running your app, but your gradle project already relies on a set of different plugins, like Java, Application or the Modular plugin. 

To help on distribution and using the jlink tool (and also the still ea jpackage tool), you can add the jlink plugin described in several places throughout the docs (gradle modular projects).

For native compilation, you may want to check the Gluon Client [plugins](https://github.com/gluonhq/client-gradle-plugin).
