### ISSUE TITLE
The ReadMe isn't good readable.

### ISSUE THREAD

**Issue by Naoghuman** [openjfx/samples#8]
The ReadMe isn't good readable.
* Momentary the ReadMe is a `endless` list of all samples.
* I find it's difficult to read and look if I want read about a special sample (e.g. NetBeans/Modular/Java).

Suggestion for the new structure:
1. Section `Description`.
2. Section `Content` contains a list from quick links (pointed to 3.) to all examples.
3. Section with all samples (e.g. tables for the 3 types of samples (java, maven, gradle)).
4. Section `License`.
5. Section `Contribution`.

**Comment by Naoghuman** [comment]
The samples here are only for `openjfx-docs`?
* So the main-title in the ReadMe can be rewritten to `OpenJFX-Docs Samples`?

**Comment by Naoghuman** [comment]
Sample of section `Content`

Content
---

* [HelloFX](#HelloFX)
    - [_CLI / Maven / Gradle sampels_](#HelloFX-Samples)
* [CommandLine](#CommandLine)
    - Non-Modular: [_CLI / Maven / Gradle sampels_](#CLI-Non-Modular-Samples)
    - Modular: [_CLI / Maven / Gradle sampels_](#CLI-Modular-Samples)

**Comment by Naoghuman** [comment]
A rewritten version of the ReadMe can be seen here:
* https://github.com/Naoghuman/samples
* Not final - see questions above.

**Comment by jperedadnr** [comment]
Looks good.
- Title can be changed, indeed, to `OpenJFX Docs Samples` or maybe to `HelloWorld Samples with JavaFX 11`?
- Your Readme looks fine, as long as you rename `sampels` to `samples` ;)
- About tools/build, I'll prefer `Build Tools`
- About HelloFX header and Sample link, I'd prefer `Sample` as header, and then `HelloFX sample` or `HelloFX project` for each row.
- For each section, before the table, don't add `CLI / Maven / Gradle sampels` to the title, just `Non-modular samples`, or `Modular samples`.
- Using IDEs, if you don't use Maven/Gradle, it doesn't mean you go to CLI to run, so we used the word `Java`, meaning that the IDE manages (with `Ant` tasks most of the times) to call the java commands. CLI will be misleading.

**Comment by Naoghuman** [comment]
* [ ] For the title I would prefer the first suggestion `OpenJFX Docs Samples` because it's more general. When a new `not` HelloWorld example will added, then the title must not refactored. __See below__.
* [x] Fix typo `sampels` to `samples`.
* [x] First column should be `Build Tools`.
* [x] Second column header is now `Sample`.
* [ ] Second row is now `HelloFX sample` / `HelloFX project`. The column is spelled `Sample`, so we should called the entry from my point of view `HelloFX project`. __See below__.
* [x] Remove `CLI / Maven / Gradles samples` in `Content` and sections. Rename them to `Non-modular samples` and `Modular samples`.
* [x] Replase first column entry `CLI` with `Java`.
* [ ] Should the first section header `Description` removed? We have the main header from the document, starting then with some basic informations about...

**Comment by Naoghuman** [comment]
* [x] Title: OpenJFX Docs Samples
* [x] Update description to: "This repository contains a collection of HelloFX samples. Each one is a very simple HelloWorld sample created with JavaFX 11 that can be run with different options and build tools."
* [x] Second column in the tables will have header=='Sample', in row=='HelloFX project'.
* [x] Title 'Description' will keep.
* [x] Fix type missing 'the' in section 'Contribution'.
* [x] Add in last section 'Contribution' a hyperlink for 'pull requests' to https://help.github.com/articles/about-pull-requests/

Update version can be found unter: https://github.com/Naoghuman/samples
For me the ReadMe looks good, so when you have nothing more then I will do a PR.

**Comment by jperedadnr** [comment]
Yes, looks fine now, go ahead with the PR, thank you.
