### ISSUE TITLE
cli example is missing the jmods folder.

### ISSUE THREAD

**Issue by odinsbane** [openjfx/samples#9]
I downloaded the most recent openjfx files and tried to use this example and I get an error about not finding the jmods for javafx. The recent sdk does not include any jmod files and I need to include --module-path $FX_SDK:$FX_JMODS to build/run the program.

**Comment by odinsbane** [comment]
Sorry, I included both of them, but it appears I need to compile with the jmods folder and run the skd/lib folder so the error is that the javac part points to the sdk, but it should point to the jmods.

**Comment by odinsbane** [comment]
To do the non-modular example I also need to use information from this post:

https://stackoverflow.com/a/52631238/2067492

And create a main class that doesn't contain any javafx stuff.

**Comment by jperedadnr** [comment]
The JavaFX 11 jmods are not distributed with the samples, they have to be downloaded, like you would download the JavaFX SDK, from the Gluon [site](https://gluonhq.com/products/javafx/) for your given platform.

As you can read in the [docs](
https://openjfx.io/openjfx-docs/#modular), you have to use jmods for creating an image with jlink. For compiling the SDK is good enough.

**Comment by odinsbane** [comment]
Yes but your example uses the LIBS for both javac and java it is a small fix in your readme.md to make it correct.

**Comment by odinsbane** [comment]
From the readme..

Compile:

javac --module-path $PATH_TO_FX --add-modules=javafx.controls HelloFX.java

**Comment by odinsbane** [comment]
Okay, on the page you reference, they say you can use either, but when I tried it I had to use the jmods directory to compile. Ill look at it again later and see if I did something else incorrect.
